name: "Update version"
on:
  push:
    branches:
    - master
    - version-update
  repository_dispatch:
    types:
    - update-on-release
  pull_request:
jobs:
  update-version:
    # TODO: Check if it's a prerelease make it multi-line
    if: github.event_name == 'repository_dispatch'
    #   && !github.event.client_payload.prerelease
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Extract version number from tag"
      id: extract-version
      run: |
        tag_name="${{ github.event.client_payload.tag }}"
        echo "Extracting version number from the tag '${tag_name}'."
        version_number="${tag_name/v/}"
        # Keep dots and count the string length
        dot_count="$(res="${version_number//[^.]/}"; echo "${#res}")"
        if [[ "${dot_count}" -eq 2 ]]; then
          version_number="${version_number}.0"
        fi
        if [[ "$(res="${version_number//[^.]/}"; echo "${#res}")" -ne 3 ]]; then
          echo "The tag '${tag_name}' is invalid" 1>&2
          exit 1
        fi
        echo "Extracted the version number '${version_number}'."
        echo "::set-output name=yb_version::${version_number}"
    - name: "Update the version of yugabytedb Formula"
      id: update-yb-formula
      run: |
        .ci/update_formula_version.sh '${{steps.extract-version.outputs.yb_version}}'
        git status
        git diff
    - name: "Run brew audit on changed Formula files"
      id: run-audit
      continue-on-error: true
      run: |
        for file in ${{steps.update-yb-formula.outputs.modified_files}}; do
          if [[ "${file}" =~ .*\/Formula\/yugabytedb(@[0-9]+\.[0-9]+)?\.rb ]]; then
            brew audit --strict --online "${file}"
          fi
        done
    - name: "Push the changes"
      if: steps.run-audit.outcome == 'success'
      run: |
        git config user.name 'YugaByte CI'
        git config user.email 'yugabyte-ci@users.noreply.github.com'
        git add ${{steps.update-yb-formula.outputs.modified_files}}
        git commit -m "Update the version to ${{steps.extract-version.outputs.yb_version}}"
        # TODO: update this before merging
        git push -f origin ${{ github.ref }}:bot-branch
    - name: "Push the changes to a branch"
      if: steps.run-audit.outcome == 'failure'
      run: |
        git status
        git diff
        git branch
        git config user.name 'YugaByte CI'
        git config user.email 'yugabyte-ci@users.noreply.github.com'
        git add ${{steps.update-yb-formula.outputs.modified_files}}
        git commit -m "Update the version to ${{steps.extract-version.outputs.yb_version}}"
        # TODO: update this before merging: remove bot-branch
        git push -f origin ${{ github.ref }}:bot-branch-update-${{steps.extract-version.outputs.yb_version}}
        echo "The run-audit step for new files has failed, please check the logs for more details" 1>&2
        # TODO: add name and URL here
        echo "The modified files are pushed to url and branch name here" 1>&2
        exit 1
