name: "Update version"
on:
  push:
    branches:
    - master
    - version-update
    # paths:
    # - ".github/workflows/packages-*.yaml"
  # pull_request:
  #   paths:
  #   - "packages/**"
  #   - ".github/workflows/packages-*.yaml"
jobs:
  update-version:
    # env:
    #   YB_VERSION: "2.1.2.0"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Update the version to 2.1.1.0"
      id: update-1
      run: |
        .ci/update_formula_version.sh '2.1.1.0'
        git status
        git diff
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb.rb
        grep "Yugabytedb" Formula/yugabytedb.rb
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb@2.0.rb
        grep "Yugabytedb" Formula/yugabytedb@2.0.rb
    - name: "Push 2.1.1.0"
      run: |
        git add ${{steps.update-1.outputs.git_modified_files}}
        git config user.name 'YugaByte CI'
        git config user.email 'yugabyte-ci@users.noreply.github.com'
        git commit -m "Update version to 2.1.1.0"
        git push -f origin ${{ github.ref }}:bot-branch
    - name: "Update the version to 2.0.11.0"
      id: update-2
      run: |
        .ci/update_formula_version.sh '2.0.11.0'
        git status
        git diff
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb.rb
        grep "Yugabytedb" Formula/yugabytedb.rb
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb@2.0.rb
        grep "Yugabytedb" Formula/yugabytedb@2.0.rb
    - name: "Push 2.0.11.0"
      run: |
        git add ${{steps.update-2.outputs.git_modified_files}}
        git config user.name 'YugaByte CI'
        git config user.email 'yugabyte-ci@users.noreply.github.com'
        git commit -m "Update version to 2.0.11.0"
        git push -f origin ${{ github.ref }}:bot-branch
    - name: "Update the version to 2.1.2.0"
      id: update-3
      run: |
        .ci/update_formula_version.sh '2.1.2.0'
        git status
        git diff
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb.rb
        grep "Yugabytedb" Formula/yugabytedb.rb
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb@2.0.rb
        grep "Yugabytedb" Formula/yugabytedb@2.0.rb
    - name: "Push 2.1.2.0"
      run: |
        git add ${{steps.update-3.outputs.git_modified_files}}
        git config user.name 'YugaByte CI'
        git config user.email 'yugabyte-ci@users.noreply.github.com'
        git commit -m "Update version to 2.1.2.0"
        git push -f origin ${{ github.ref }}:bot-branch
    - name: "Update the version to 3.0.0.0"
      id: update-4
      run: |
        .ci/update_formula_version.sh '3.0.0.0' || true
        git status
        git diff
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb.rb
        grep "Yugabytedb" Formula/yugabytedb.rb
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb@2.1.rb
        grep "Yugabytedb" Formula/yugabytedb@2.1.rb
        grep -E "^[[:space:]]+url" ./Formula/yugabytedb@2.0.rb
        grep "Yugabytedb" Formula/yugabytedb@2.0.rb
    - name: "Push 3.0.0.0"
      run: |
        git add ${{steps.update-4.outputs.git_modified_files}}
        git config user.name 'YugaByte CI'
        git config user.email 'yugabyte-ci@users.noreply.github.com'
        git commit -m "Update version to 3.0.0.0"
        git push -f origin ${{ github.ref }}:bot-branch
    # - name: "Update the version to a newer version"
    #   run: |
    #     .ci/update_formula_version.sh "${YB_VERSION}"
    # - name: "Run git commands"
    #   run: |
    #     git status
    #     git diff
        # git add -u
        # git config user.name 'Bhavin Gandhi'
        # git config user.email 'bhavin192@users.noreply.github.com'
        # git commit -m "Update version to ${YB_VERSION}"
        # git push origin ${{ github.ref }}:bot-branch
