name: "Test Formula installation"
on:
  push:
    branches:
    - java-fix
jobs:
  install-formula:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Add yugabytedb tap and checkout development branch"
      run: |
        brew tap yugabyte/yugabytedb file://$(pwd)
        brew install --build-from-source yugabyte/yugabytedb/yugabytedb
        which ysqlsh || true
        which ycqlsh || true
        which cqlsh || true
        timeout 10m yugabyted start --config /usr/local/etc/yugabyte.conf

